services:
  26x:
    build: ./
    volumes:
      - ./test_ws:/home/26x/test_ws
      - ./rosbags:/home/26x/rosbags
    user: "1001:1001"
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    ports:
      - "8765:8765"
    stdin_open: true
    tty: true
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
