services:
  26x:
    build: 
      context: ./
      secrets:
        - github_pat
      args:
        GITHUB_USERNAME: "$GH_USER"
    volumes:
      - ./test_ws:/root/test_ws
      - ./rosbags:/root/rosbags
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    ports:
      - "8765:8765"
    stdin_open: true
    tty: true
  ml-dev:
    build:
      context: ./docker/ml-dev
      dockerfile: ml.Dockerfile
    volumes:
      - ./ml_data:/root/ml_data
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    ports:
      - 5001:5000
    command: sleep infinity
    stdin_open: true
    tty: true
  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
secrets:
  github_pat:
    environment: GITHUB_PAT
