services:
  26x:
    build:
      context: ./docker/26x
      dockerfile: Dockerfile
      secrets:
        - github_pat
      args:
        GITHUB_USERNAME: "$GH_USER"
    volumes:
      - ./test_ws:/root/test_ws
      - ./rosbags:/root/rosbags
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    ports:
      - "8765:8765"
    stdin_open: true
    tty: true

  ml-dev:
    profiles: ["ml-dev"]
    build:
      context: ./docker/ml-dev
      dockerfile: ml.Dockerfile
    volumes:
      - ./ml_data:/root/driverless-ml-dev/ml_data
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    ports:
      - 5001:5000
    command: sleep infinity
    stdin_open: true
    tty: true
    # Uncomment to enable GPU support for training
    # Note: Requires Nvidia Container Toolkit installed on host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  harness:
    profiles: ["harness"]
    build:
      context: ./docker/harness
      dockerfile: Dockerfile
    gpus: all
    volumes:
      - ${DRIVERLESS}:/root/driverless
      - ./docker/harness:/root/harness
      - ${LIBS}/canUsbKvaserTesting/linuxcan:/root/canUsbKvaserTesting/linuxcan
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LD_LIBRARY_PATH=/root/canUsbKvaserTesting/linuxcan/canlib
    working_dir: /root/harness
    command: sleep infinity
    stdin_open: true
    tty: true

  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:

secrets:
  github_pat:
    environment: GH_PAT
